### ISSUE TITLE
Add option to specify types of locations

### ISSUE THREAD

**Issue by pedro-stanaka** [varsitynewsnetwork/php-google-places-api#6]
Hello, first I'd like to thank you for your work! And then, I'd like to ask you to add support to specify which types of location I want google to return (e.g. schools, restaurants).

Cheers!

**Comment by austinsmorris** [comment]
Hi @pedro-stanaka,

We currently don't have any plans to work on this library.  But, since it is open source, please consider submitting a pull request with the features you desire and we will review it.

Thanks!

**Comment by boboudreau** [comment]
Hi @pedro-stanaka,

VNN has recently required some work on this library which now allows you to specify location types. I'm sure you've figured out your own solution by now, but this issue can now be closed with the release of version 2.1 of this library.
